package com.kyowon.sms.wells.web.contract.interfaces.dvo;

import com.sds.sflex.system.config.annotation.DBDecField;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class WctiContractDetailInfoDvo {
    private String cntrNo; // 계약번호
    private Integer cntrSn; // 계약일련번호
    private String cntrDtlStatCd; // 계약상세상태코드
    private String cntrDtlStatNm; // 계약상세상태코드명
    private String copnDvCd; // 법인격구분코드
    private String sellTpCd; // 판매유형코드
    private String sellTpNm; // 판매유형명
    private String sellTpDtlCd; // 판매유형상세코드
    private String sellTpDtlNm; // 판매유형상세명
    private String sellInflwChnlDtlCd; // 판매유입채널상세코드
    private String sellInflwChnlDtlNm; // 판매유입채널상세명
    private String cntrDtlStatChRsonCd; // 계약상세상태변경사유코드
    private String cntrDtlStatChRsonNm; // 계약상세상태변경사유명
    private String cntrCstNo; // 계약자고객번호
    private String cntrCstNm; // 계약자고객명
    private String bryyMmdd; // 생년월일
    private String sexDvCd; // 성별구분코드
    private String basePdCd; // 기준상품코드
    private String basePdNm; // 기준상품명
    private String svPdCd; // 서비스상품코드
    private String svPdNm; // 서비스상품명
    private Integer pdQty; // 상품수량
    private String pdHclsfId; // 상품대분류ID
    private String pdHclsfNm; // 상품대분류명
    private String pdMclsfId; // 상품중분류ID
    private String pdMclsfNm; // 상품중분류명
    private String pdLclsfId; // 상품소분류ID
    private String pdLclsfNm; // 상품소분류명
    private String pdDclsfId; // 상품세분류ID
    private String pdDclsfNm; // 상품세분류명
    private String cntrRcpDt; // 계약접수일자
    private String cntrCnfmDt; // 계약확정일자
    private String cntrPdStrtdt; // 상품시작일자
    private String cntrPdEnddt; // 상품종료일자
    private String cntrCralLocaraTno; // 휴대지역전화번호
    @DBDecField
    private String cntrMexno; // 휴대전화국번호
    private String cntrCralIdvTno; // 휴대개별전화번호
    private String cntrLocaraTno; // 지역전화번호
    @DBDecField
    private String cntrExno; // 전화국번호
    private String cntrIdvTno; // 개별전화번호
    private String cntrAdrId; // 계약주소ID
    private String cntrAdr; // 계약주소
    private String cntrDtlAdr; // 계약상세주소
    private String cntrAdrZip; // 계약우편번호
    private String istCstNm; // 설치고객명
    private String cralLocaraTno; // 휴대지역전화번호
    @DBDecField
    private String mexno; // 휴대전화국번호
    private String cralIdvTno; // 휴대개별전화번호
    private String locaraTno; // 지역전화번호
    @DBDecField
    private String exno; // 전화국번호
    private String idvTno; // 개별전화번호
    private String adrId; // 설치지주소ID
    private String adr; // 설치지주소
    private String dtlAdr; // 설치지상세주소
    private String adrZip; // 설치지우편번호
    private String vstRqdt; // 방문요청일자
    private String sppMthdTpCd; // 배송방식유형코드
    private String sppMthdTpCdNm; // 배송방식유형코드명
    private String sppIchrAoffceCd; // 배송담당사무소코드
    private String sppIchrAoffceNm; // 배송담당사무소명
    private String booSellTpCd; // 예약판매유형코드
    private String coCd; // 소속법인코드
    private String coNm; // 소속법인코드명
    private Integer cntrTam; // 계약총액
    private Integer sellAmt; // 판매금액
    private Integer dscAmt; // 할인금액
    private Integer fnlAmt; // 최종금액
    private Integer cntrAmt; // 계약금액
    private Integer istmPcamAmt; // 할부원금금액
    private Integer mmIstmAmt; // 월할부금액
    private Integer istmIntAmt; // 할부이자금액
    private Integer dpTotAmt; // 입금금액
    private Integer bltfAmt; // 전금금액
    private Integer rfndAmt; // 환불금액
    private Integer ucTotAmt; // 미수총금액
    private Integer feeAckmtBaseAmt; // 수수료인정기준금액
    private Integer dlqMcn; // 연체개월수
    private Integer dlqAmt; // 연체금액
    private Integer cntrPtrm; // 계약기간
    private String sppDuedt; // 배송예정일자
    private String istDt; // 설치일자
    private String reqdDt; // 철거일자
    private String canDt; // 취소일자
    private String slDt; // 매출일자
    private String cpsDt; // 보상일자
    private String ensmCntrYn; // 임직원계약여부
    private String mchnChYn; // 기기변경여부
    private String mchnChTpCd; // 기기변경유형코드
    private String mchnChTpCdNm; // 기기변경유형코드명
    private String mchnChOjCntrNo; // 기기변경대상계약번호
    private Integer mchnChOjCntrSn; // 기기변경대상계약일련번호
    private String sellEvCd; // 판매행사코드
    private String cstStlmInMthCd; // 고객결제입력방법코드
    private Integer rentalTn; // 렌탈회차
    private Integer stplPtrm; // 약정기간
    private Integer frisuBfsvcPtrmN; // 무상BS기간수
    private Integer frisuAsPtrmN; // 무상AS기간수
    private String urgtOjYn; // 긴급대상여부
    private String frisuYn; // 무상여부
    private String alncmpCd; // 제휴사코드
    private String alncmpNm; // 제휴사명
    private String alncDv; // 제휴구분
    private String cntrChRcpId; // 계약변경접수ID
    private String cntrChFshDt; // 계약변경완료일자
    private String cntrChTpCd; // 계약변경유형코드
    private String cntrChTpNm; // 계약변경유형명
    private String cttPsicId; // 컨택담당자ID
    private String cttPsicNm; // 컨택담당자명
    private String cttRsCd; // 컨택결과코드
    private String cttRsCdNm; // 컨택결과코드명
    private String cttAkRsonCd; // 컨택요청사유코드
    private String cttAkRsonNm; // 컨택요청사유명
    private String cttMoCn; // 컨택메모내용
    private String cttFshDtm; // 컨택완료일시
    private String cttExpDvCd; // 컨택예정구분코드
    private String cttExpDvCdNm; // 컨택예정구분코드명
    private String fntDt; // 이체일자
    private String dpTpCd; // 입금유형코드
    private String fnitAprRsCd; // 금융기관승인결과코드
    private String sellPrtnrNo; // 판매파트너번호
    private String sellPrtnrNm; // 판매파트너명
    private String sellOgCd; // 판매조직코드
    private String sellOgNm; // 판매조직명
    private String clctamPrtnrNo; // 집금파트너번호
    private String clctamPrtnrNm; // 집금파트너명
    private String prtnrCntrYn; // 판매자계약건여부
    private String txinvPblOjYn; // 세금계산서발행대상여부
    private String sellDscTpCd; // 판매할인유형코드
    private String sellDscTpNm; // 판매할인유형명
    private String sellDscDvCd; // 판매할인구분코드
    private String sellDscDvNm; // 판매할인구분명
    private String sellDscrCd; // 판매할인율코드
    private Integer sellDscCtrAmt; // 판매할인조정금액
    private String onePlusOneDlYn; // 1+1삭제여부
    private Integer rentalAdnSvCt; // 렌탈부가서비스건수
    private String rentalAdnSvReqdDt; // 렌탈부가서비스철거일자
    private String stplYn; // 재약정여부
    private String stplCanDt; // 재약정취소일자
    private String stplEnddt; // 재약정종료일자
    private String sdingCombiYn; // 모종결합여부
    private String svPrd; // 서비스주기
    private String svTpCd; // 용도구분
    private String sconCn; // 특약내용
    private String srcwtTpCd; // 상수원유형코드
    private String wtqltyTstYn; // 수질검사여부
    private String istPlcTpCd; // 설치장소유형코드
    private String wrfrIstMthCd; // 정수기설치방법코드
    private String istBzsCd; // 설치업체
    private String svIstPcsvDvCd; // 설치택배구분
    private String frisuRcvryTpCd; // 무상복구유형코드
    private String filtEnddt; // 최종멤버십종료일자
    private String svVstPrdCd; // 방문주기
    private String pcsvPrdCd; // 택배주기
    private Integer istmMcn; // 할부개월수
    private String bfsvcBzsDvCd; // BS업체구분코드
    private String cntrSfkVal; // 계약자세이프키값
    private String prtnrBzsCd; // 파트너업체코드
    private String prtnrBzsNm; // 파트너업체명
    private String prtnrBzsCtplc; // 파트너업체연락처
    private String ojCntrNo; // 대상계약번호
    private Integer ojCntrSn; // 대상계약일련번호
    private String ojSellTpCd; // 대상판매유형코드
    private String ojSellTpNm; // 대상판매유형명
    private String ojIstDt; // 대상설치일자
    private String stlmTpCd; // 결제유형코드
    private String hcrMshDvCd; // 홈케어멤버십구분코드
    private String cltnDt; // 해약일자
    private String cltnAskDt; // 해약요청일자
    private String rglrSppPrcDvCd; // 정기배송가격구분코드
    private String islndYn; // 도서지역여부
    private String coIstMngtDvCd; // 회사설치관리구분코드
    private String coIstUswyCd; // 회사설치용도코드
    private String istAkArtcMoCn; // 설치요청사항메모내용
    private String fstRgstDtm; // 최초등록일시
    private String fstRgstUsrId; // 최초등록사용자ID
    private String fstRgstUsrNm; // 최초등록사용자명
    private String fnlMdfcDtm; // 최종수정일시
    private String fnlMdfcUsrId; // 최종수정사용자ID
    private String fnlMdfcUsrNm; // 최종수정사용자명
}


