-- TEST DATA 추출
SELECT *
FROM TB_SVPD_CST_SVAS_IST_ASN_IZ S1
         INNER JOIN TB_SVPD_CST_SVAS_IST_OJ_IZ S2
                    ON S1.CST_SV_ASN_NO = S2.CST_SV_ASN_NO
         INNER JOIN TB_SSCT_CNTR_DTL C1
                    ON S2.CNTR_NO = C1.CNTR_NO
                        AND S2.CNTR_SN = C1.CNTR_SN
WHERE 1 = 1
  AND S1.SV_BIZ_DCLSF_CD = '1110'
  AND S1.VST_CNFMDT LIKE '202306%'
  AND S2.IN_CHNL_DV_CD = '4'
  AND S2.MTR_STAT_CD = '1'
  AND S2.CNTR_NO = 'W20234652781';

-- 데이터 삭제
DECLARE
    vCntrNo VARCHAR2(200);
    vCntrSn VARCHAR2(200);
BEGIN
    vCntrNo := 'W20234744415';
    vCntrSn := '1';

    DELETE
    FROM TB_SVPD_CST_SVAS_IST_OJ_IZ T1
    WHERE T1.CNTR_NO = vCntrNo
      AND T1.CNTR_SN = vCntrSn;

    DELETE
    FROM TB_SVPD_CST_SVAS_IST_ASN_IZ T1
    WHERE T1.CNTR_NO = vCntrNo
      AND T1.CNTR_SN = vCntrSn;
END;
